# awful security practice,
# consider creating a new
# user with secure generated credentials!
loopback_users = none

ssl_options.cacertfile = /Certs/ca.pem
ssl_options.certfile   = /Certs/server.pem
ssl_options.keyfile    = /Certs/server.key
ssl_options.verify     =  verify_peer
ssl_options.fail_if_no_peer_cert = true

stomp.listeners.tcp.1 = 61613
# default TLS-enabled port for STOMP connections
stomp.listeners.ssl.1 = 61614

web_stomp.ssl.port       = 15673
web_stomp.ssl.backlog    = 1024
web_stomp.ssl.cacertfile = /Certs/ca.pem
web_stomp.ssl.certfile   = /Certs/server.pem
web_stomp.ssl.keyfile    = /Certs/server.key
web_stomp.ssl.password   = STOMPNIOClientCertPassword