name: CI

on:
   push:
     branches:
     - main
   pull_request:
     branches:
     - main
   release:
     types: [published]
   workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-ci
  cancel-in-progress: true

jobs:
  linux-unit:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        tag:
          - swift:6.2
    container:
      image: ${{ matrix.tag }}
    services:
      rabbitmq:
        image: rabbitmq:3.13
        ports:
          - 5672:5672
          - 61613:61613
        options: >-
          --health-cmd "rabbitmq-diagnostics -q ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        volumes:
          - ${{ github.workspace }}/.github/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Test
      env:
        STOMP_SERVER: rabbitmq
      run: swift test

  lint:
    runs-on: ubuntu-latest
    container: swift:noble
    timeout-minutes: 5
    steps:
      - name: Configure git
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"
      - name: Check out code
        uses: actions/checkout@v6
      - name: Lint
        run: |
          apt -q update && apt -yq install curl
          curl -s https://raw.githubusercontent.com/swiftlang/github-workflows/refs/heads/main/.github/workflows/scripts/check-swift-format.sh | bash