name: CI

on:
   push:
     branches:
     - main
   pull_request:
     branches:
     - main
   release:
     types: [published]
   workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-ci
  cancel-in-progress: true

jobs:
  macos-unit:
    strategy:
      matrix:
        macos-version:
          - macos-15
          - macos-26
    runs-on: ${{ matrix.macos-version }}
    timeout-minutes: 15
    steps:
    - name: Select appropriate Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Check out code
      uses: actions/checkout@v6
    - name: Install and run RabbitMQ
      run: |
        brew install rabbitmq
        rabbitmq-plugins enable rabbitmq_stomp rabbitmq_web_stomp
        RABBITMQ_CONFIG_FILE=./RabbitMQ/rabbitmq rabbitmq-server -detached
    - name: Run unit tests
      run: swift test --enable-code-coverage
    - name: Upload coverage data
      uses: vapor/swift-codecov-action@v0.3
      with:
        codecov_token: ${{ secrets.CODECOV_TOKEN }}

  ios-build:
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
    - name: Select appropriate Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Check out code
      uses: actions/checkout@v6
    - name: Xcodebuild
      run: |
        xcodebuild build -scheme stomp-nio -destination 'platform=iOS Simulator,name=iPhone 17'

  linux-unit:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        tag:
          - swift:6.2
    container:
      image: ${{ matrix.tag }}
    services:
      rabbitmq:
        image: rabbitmq:latest
        options: --hostname rabbitmq --name rabbitmq
        ports:
          - 61613:61613
          - 15674:15674
          - 61614:61614
          - 15673:15673
        volumes:
          - ${{ github.workspace }}/RabbitMQ:/etc/rabbitmq
          - ${{ github.workspace }}/Certs:/Certs
    steps:
    - name: Install curl
      run: apt-get update -yq && apt-get install -y curl
    - name: Check out code
      uses: actions/checkout@v6
    - name: Restart RabbitMQ
      uses: docker://docker
      with:
        args: docker restart rabbitmq
    - name: Run unit tests
      env:
        RABBITMQ_SERVER: rabbitmq
      run: swift test --enable-code-coverage
    - name: Upload coverage data
      uses: vapor/swift-codecov-action@v0.3
      with:
        codecov_token: ${{ secrets.CODECOV_TOKEN }}

  android-build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Build for Android
        uses: skiptools/swift-android-action@v2
        with:
          build-tests: true
          run-tests: false

  package-traits:
    runs-on: ubuntu-latest
    container: swift:6.2-bookworm
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Run tests with traits disabled
        run: swift test --disable-default-traits

  lint:
    runs-on: ubuntu-latest
    container: swift:noble
    timeout-minutes: 5
    steps:
      - name: Configure git
        run: git config --global --add safe.directory "${GITHUB_WORKSPACE}"
      - name: Check out code
        uses: actions/checkout@v6
      - name: Lint
        run: |
          apt -q update && apt -yq install curl
          curl -s https://raw.githubusercontent.com/swiftlang/github-workflows/refs/heads/main/.github/workflows/scripts/check-swift-format.sh | bash